[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "pulp know nature faint era buyer what large test measure naive develop system alpha lemon road enough peace raccoon illegal rug park unable floor"
